# Site settings
title: Saurabh Pandit | Drupal Developer
description: My portfolio blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Saurabh Pandit
user_description: Hey there! Im primarily a Drupal Backend developer with over 9 years of extensive experience in developing drupal web application across multiple domains like Ecommerce, Education, Healthcare etc. Ive worked in drupal projects of varying complexies and diverse application and requirements. I'm currently based in Mumbai.
user_title: Drupal Developer
email: saurabh.pandit26@gmail.com
twitter_username: saurabhpandit26
github_username:  saurabhpandit26
gplus_username:  saurabhpandit

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
